---
name: "Java CI"
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"
          cache: maven
      - name: Compile and run tests with maven
        run: mvn -B verify
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: example
          path: example*/target/**
