---
name: "Java CI"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Setup java 11"
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: "Compile and run tests with maven"
        run: "mvn -B verify"
      - name: "Upload artifact 1"
        uses: actions/upload-artifact@v1
        with:
          name: "example1"
          path: example1/target
      - name: "Upload artifact 2"
        uses: actions/upload-artifact@v1
        with:
          name: "example2"
          path: example2/target
      - name: "Upload artifact 3"
        uses: actions/upload-artifact@v1
        with:
          name: "example3"
          path: example3/target
      - name: "Upload artifact 4"
        uses: actions/upload-artifact@v1
        with:
          name: "example4"
          path: example1/target
      - name: "Upload artifact 5"
        uses: actions/upload-artifact@v1
        with:
          name: "example5"
          path: example5/target
      - name: "Upload artifact 6"
        uses: actions/upload-artifact@v1
        with:
          name: "example6"
          path: example6/target
      - name: "Upload artifact 7"
        uses: actions/upload-artifact@v1
        with:
          name: "example7"
          path: example7/target
      - name: "Upload artifact 8"
        uses: actions/upload-artifact@v1
        with:
          name: "example8"
          path: example8/target
      - name: "Upload artifact 9"
        uses: actions/upload-artifact@v1
        with:
          name: "example9"
          path: example9/target
      - name: "Upload artifact 10"
        uses: actions/upload-artifact@v1
        with:
          name: "example10"
          path: example10/example10-cli/target
      - name: "Upload artifact 11"
        uses: actions/upload-artifact@v1
        with:
          name: "example11"
          path: example11/example11-cli/target
      - name: "Upload artifact 12"
        uses: actions/upload-artifact@v1
        with:
          name: "example12"
          path: example12/target
      - name: "Upload artifact 13"
        uses: actions/upload-artifact@v1
        with:
          name: "example13"
          path: example13/target
